[workspace]

members = [
    "auditable",
    "auditable-build",
    "auditable-extract",
    "auditable-inject",
    "auditable-serde",
    "cargo-auditable",
    "hello-auditable",
    "rust-audit-info",
]
