[package]
name = "auditable-serde"
version = "0.0.1"
authors = ["Sergey \"Shnatsel\" Davidoff <shnatsel@gmail.com>"]
description = "Serialize/deserialize data encoded by `auditable`"
edition = "2018"

[features]
default = ["toml"]
toml = ["cargo-lock"]

[dependencies]
serde = { version = "1", features = ["serde_derive"] }
serde_json = "1.0.57"
cargo-lock = { version = "4.0.1", default-features = false, optional = true }