[package]
name = "auditable-serde"
version = "0.0.1"
authors = ["Sergey \"Shnatsel\" Davidoff <shnatsel@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/Shnatsel/rust-audit"
description = "Serialize/deserialize data encoded by `auditable` crate"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-lock = { version = "4.0.1", default-features = false }
serde = { version = "1", features = ["serde_derive"] }
serde_json = "1.0.57"
