[package]
name = "gen_manpage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
man = "0.3"

# Exclude the manpage generator from the main workspace
[workspace]