[package]
name = "cargo-auditable"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-subcommand = "0.5.0"
object = {version = "0.28.1", default-features = false, features = ["write"]}
auditable-serde = {path = "../auditable-serde", features = ["from_metadata"]}
miniz_oxide = {version = "0.5.0"}
serde_json = "1.0.57"
cargo_metadata = "0.15"