[package]
name = "auditable-inject"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
object = {version = "0.28.1", default-features = false, features = ["write"]}
