name: Linux

on:
  pull_request: {}
  push:
    branches: master

jobs:
  test:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
        toolchain:
          - stable
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('Cargo.lock') }}
      - uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
          override: true
          target: "i686-unknown-linux-gnu"
      - run: cargo test --all-features # default x86_64-unknown-linux-gnu
      - run: cargo test --all-features
        env:
          AUDITABLE_TEST_TARGET: "i686-unknown-linux-gnu"
